# Introdução {#sec-intro}

De acordo com o CTB (Código de Trânsito Brasileiro), os Departamentos Estaduais de Trânsito (Detran) têm como competências o planejamento, coordenação, execução e controle relacionados às seguintes áreas: habilitação de condutores, veículos, fiscalização de trânsito, estatísticas e educação para o trânsito. 

Considerando o processo de habilitação de condutores, cabe ao Detran realizar e controlar o processo de formação, reciclagem e suspensão dos condutores, assim como a expedição e cassação da Licença de Aprendizagem, Permissão para Dirigir e CNH (Carteira Nacional de Habilitação). Já em relação aos veículos motorizados, compete ao Detran o seu registro, emplacamento, licenciamento e a expedição do seu Certificado de Registro e Licenciamento Anual.

Na área de fiscalização, o Detran deve fazer cumprir a legislação e as normas de trânsito, sendo responsável pela autuação e aplicação de medidas administrativas cabíveis pelas infrações previstas no Código de Trânsito Brasileiro. As questões de educação para o trânsito também são de responsabilidade do Detran, incluindo a promoção e participação de projetos de educação e segurança no trânsito. 

Em relação aos dados estatísticos, os Detrans gerenciam um grande número de informações relevantes para a gestão do trânsito e da segurança viária no país, com destaque para as temáticas das infrações de trânsito, sinistros de trânsito e condutores habilitados, de modo que a disponibilização pública desse conteúdo contribui para subsidiar análises críticas acerca de temas relacionados à mobilidade segura em todo território nacional.

Todo o processo de gestão e disponibilização de dados estatísticos sobre mobilidade é um fator de importância para a execução do Plano Nacional de Redução de Mortes e Lesões no Trânsito (Pnatrans), considerando principalmente o Pilar I - Gestão da Segurança no Trânsito.

## Objetivo {#sec-intro-obj}

O objetivo principal desse trabalho é apresentar uma avaliação do nível de informações disponibilizadas nos portais (sítios eletrônicos) dos Detrans de todas as unidades da federação brasileira^[Recentemente, após uma reforma administrativa da estrutura do Estado de Minas Gerais, o antigo Detran MG deixou de integrar a estrutura da Polícia Civil e passou a fazer parte da Secretaria de Estado de Planejamento e Gestão (Seplag), recebendo o nome de Coordenadoria Estadual de Gestão de Trânsito (CET-MG). Elevada à posição de subsecretaria, a Coordenadoria Estadual de Gestão de Trânsito absorveu todas as competências anteriormente desempenhadas pelo Detran. Assim, no caso do Estado de Minas Gerais, os resultados aqui apresentados são relativos ao portal da CET-MG.]. Esta avaliação teve como propósito verificar o desempenho dos Departamentos Estaduais de Trânsito (Detrans) em relação à disponibilização de informações.

Os Detrans, por sua atuação, trabalham com um grande número de informações relevantes para a gestão do trânsito no país, tendo muitas delas, além do teor formal e burocrático, uma grande utilidade para avaliações no âmbito da segurança viária, tais como: infrações de trânsito, sinistros de trânsito, e habilitação, entre outros.

Nesse sentido, este documento busca apresentar uma análise da situação das informações disponibilizadas nos portais de cada Detran^[Ou CET-MG, no caso de Minas Gerais], permitindo obter um panorama de como essas instituições trabalham e disponibilizam informações de interesse social.

Além da introdução, o documento compõe-se das seguintes seções: @sec-method, com as consultas preliminares, pontuação e critérios estabelecidos; @sec-results, com a pontuação geral em cada categoria analisada e com a evolução das notas resultantes ao longo dos anos; e @sec-conclusion, com as considerações finais. Como apêndices, @sec-praticas apresenta exemplos de boas práticas encontradas nos sítios eletrônicos e @sec-links inclui os links de acesso para as páginas consideradas na análise.
