#!/bin/bash

quarto render avaliacao.qmd -P state:"AC" -o avaliacao_AC.pdf
quarto render avaliacao.qmd -P state:"AL" -o avaliacao_AL.pdf
quarto render avaliacao.qmd -P state:"AP" -o avaliacao_AP.pdf
quarto render avaliacao.qmd -P state:"AM" -o avaliacao_AM.pdf
quarto render avaliacao.qmd -P state:"BA" -o avaliacao_BA.pdf
quarto render avaliacao.qmd -P state:"CE" -o avaliacao_CE.pdf
quarto render avaliacao.qmd -P state:"DF" -o avaliacao_DF.pdf
quarto render avaliacao.qmd -P state:"ES" -o avaliacao_ES.pdf
quarto render avaliacao.qmd -P state:"GO" -o avaliacao_GO.pdf
quarto render avaliacao.qmd -P state:"MA" -o avaliacao_MA.pdf
quarto render avaliacao.qmd -P state:"MT" -o avaliacao_MT.pdf
quarto render avaliacao.qmd -P state:"MS" -o avaliacao_MS.pdf
quarto render avaliacao.qmd -P state:"MG" -o avaliacao_MG.pdf
quarto render avaliacao.qmd -P state:"PA" -o avaliacao_PA.pdf
quarto render avaliacao.qmd -P state:"PB" -o avaliacao_PB.pdf
quarto render avaliacao.qmd -P state:"PR" -o avaliacao_PR.pdf
quarto render avaliacao.qmd -P state:"PE" -o avaliacao_PE.pdf
quarto render avaliacao.qmd -P state:"PI" -o avaliacao_PI.pdf
quarto render avaliacao.qmd -P state:"RJ" -o avaliacao_RJ.pdf
quarto render avaliacao.qmd -P state:"RN" -o avaliacao_RN.pdf
quarto render avaliacao.qmd -P state:"RS" -o avaliacao_RS.pdf
quarto render avaliacao.qmd -P state:"RO" -o avaliacao_RO.pdf
quarto render avaliacao.qmd -P state:"RR" -o avaliacao_RR.pdf
quarto render avaliacao.qmd -P state:"SC" -o avaliacao_SC.pdf
quarto render avaliacao.qmd -P state:"SP" -o avaliacao_SP.pdf
quarto render avaliacao.qmd -P state:"SE" -o avaliacao_SE.pdf
quarto render avaliacao.qmd -P state:"TO" -o avaliacao_TO.pdf